services:
  streamlit:
    build:
      dockerfile: Dockerfile
      context: streamlit
    ports:
      - '8501:8501'
    restart: unless-stopped

  api:
    build:
      dockerfile: Dockerfile
      context: api
    ports:
      - '8000:8000'
    restart: unless-stopped